name: "Push_Web_to_Azure_Storage_and_Purge_CDN"

on:
  push:
    branches: [ "main" ]
    paths:
        - 'web/**'

permissions:
  contents: read

jobs:
  Push_Web_to_Azure_Storage_and_Purge_CDN:
    name: "Push_Web_to_Azure_Storage_and_Purge_CDN"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v2
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --overwrite --account-name "jpolanskyresume" --auth-mode key -d '$web' -s web

    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "resume-cdn-profile" --name "resume-cdn-endpoint" --resource-group "Az-Resume"

    - name: logout
      run: |
            az logout
      if: always()