name: Deploy Function App

on:
  push:
    branches: [ "main" ]
    paths:
        - 'function/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./function/requirements.txt

    - name: 'Deploy to Azure Functions'
      uses: azure/functions-action@v1
      id: fa
      with:
        app-name: jpolanskyresume-functionapp
        package: ./function
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        respect-funcignore: true
        scm-do-build-during-deployment: true
        enable-oryx-build: true