name: "Terraform - Every 30 Days"

on:
  schedule:
    - cron: "0 0 13 * *"

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: self-hosted

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
    
    - name: Install unzip
      run: sudo apt-get install -y unzip

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false