name: "Push_Web_to_Azure_Storage_and_Purge_CDN"

on:
  push:
    branches: [ "main" ]
    paths:
        - 'web/**'

permissions:
  contents: read

jobs:
  Push_Web_to_Azure_Storage_and_Purge_CDN:
    name: "Push_Web_to_Azure_Storage_and_Purge_CDN"
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install Azure CLI
      run: |
        echo ${{ secrets.USERPWD }} | sudo -S apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
        curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
        AZ_REPO=$(lsb_release -cs)
        echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
        sudo apt-get update
        sudo apt-get install azure-cli

    - name: Login to Azure  
      uses: azure/login@v2
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload web files to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --overwrite --account-name "jpolanskyresume" --auth-mode key -d '$web' -s web

    - name: Upload blog files to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --overwrite --account-name "jpolanskyresume" --auth-mode key -d 'admin' -s admin

    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "resume-cdn-profile" --name "resume-cdn-endpoint" --resource-group "Az-Resume"

    - name: logout
      run: |
            az logout
      if: always()